### ISSUE TITLE
Help with Linux Support

### ISSUE THREAD

**Issue by JustOneMoreBlock** [SergiX44/Rocket_Manager#1]
Here's a few issues with running on Linux. (Tested on CentOS 6.x x64)

http://i.imgur.com/3YoLmWs.png
http://i.imgur.com/rfWzbaK.png

http://pastebin.com/raw.php?i=LGXTW7hx

**Comment by sergix44** [comment]
For now the manager work only on windows for now.

**Comment by Gameplayer01** [comment]
So it was not yet implemented the linux support?
Then what's this?:
#For Linux

URL_ROCKET_LINUX = "http://api.rocket.foundation/download/unturned-linux/latest/"
URL_STEAM_LINUX = "https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"

PROCNAME_WIN = "Unturned.exe"

**Comment by sergix44** [comment]
This is a beginning for the Linux support. I have a build that work with linux on my PC that it seems to work, but it's not ready yet.
Also, i'm working on the v2 of the manager, that will be multi game(not only for unturned) and with a web interface.

**Comment by Gameplayer01** [comment]
Ok. I wait anxiously the linux support   :+1:    ;-)
Thanks for the answer.
have a good day

**Comment by sergix44** [comment]
Support added.
