### ISSUE TITLE
Script dies when unable to download rocketmod

### ISSUE THREAD

**Issue by XimmersiveX** [SergiX44/Rocket_Manager#5]
Rocketmod.net has been down for over 4 hours. The game hasn't updated so the current rocketmod should still be valid and working, but since rocketmod.net is down, the script dies since it can't download a fresh copy of rocketmod.

Is there a way you could update this so it will still try to start the server even if rocketmod download is not working?

I have looked through the code to see if I could figure out how to stop it drom killing itself but I guess this stuff is still just to above my head for the time time being.

**Comment by JustOneMoreBlock** [comment]
Temporarily, you can go in the config of RocketManager:

Change
```
<rocket useRocket="true"
```
to
```
<rocket useRocket="false"
```

**Comment by XimmersiveX** [comment]
I actually found the section of code responsible for downloading rocket and deleted that whole part. This has been my first time ever looking at python code and I'm actually excited to see how you fix this. I seem to be able to follow your code and what you have done relatively well. My thoughts is something to do with ```break``` but how to get it to pass everything and go on is beyond me.

**Comment by sergix44** [comment]
Simply there isn't a check if the rocket api is online, the script retry every 5 seconds for 5 times, if it still have the download error, the script dies.
I will fix the issue soon, because also my servers are down.

**Comment by sergix44** [comment]
Fixed here: https://github.com/SergiX44/Rocket_Manager/commit/66ce575592bf4265b3e78dc4426b8d6a2e2c9742
