### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by leo65** [SergiX44/Rocket_Manager#6]
C:\testserver>Rocket_Manager_v1.9.4.pyo
  File "C:\testserver\Rocket_Manager_v1.9.4.pyo", line 1
SyntaxError: Non-UTF-8 code starting with '\xf3' in file C:\testserver\Rocket_Ma
nager_v1.9.4.pyo on line 1, but no encoding declared; see http://python.org/dev/
peps/pep-0263/ for details

**Comment by sergix44** [comment]
Python version? OS?
Need more infos.
Launch the script with `python <script name>`
